from sqlalchemy.orm import Session
from sqlalchemy import desc # For ordering

from . import database # This refers to database.py where SQLAlchemy models are defined
from . import schemas # This refers to schemas.py where Pydantic models are defined

def create_note(db: Session, note: schemas.NoteCreate) -> database.Note: # Use schemas.NoteCreate
    db_note = database.Note(content=note.content) # timestamp is auto-generated by default in the model
    db.add(db_note)
    db.commit()
    db.refresh(db_note)
    return db_note

def get_notes(db: Session, skip: int = 0, limit: int = 100) -> list[database.Note]:
    return db.query(database.Note).order_by(desc(database.Note.timestamp)).offset(skip).limit(limit).all()
